?start: formula

formula: TEMPLATE_NAME "(" args ")"
args: arg ("," arg)*
?arg: bool_expr | number

?bool_expr: bool_or
?bool_or: bool_and
        | bool_or "|" bool_and
?bool_and: bool_unary
         | bool_and "&" bool_unary
?bool_unary: "!" bool_unary -> bool_neg
           | proposition
           | "(" bool_or ")"
proposition: PROP

PROP: /[a-zA-Z_][a-zA-Z0-9_]*/
number: INT
TEMPLATE_NAME: /[a-zA-Z0-9_-]+/

%import common.INT
%import common.WS
%ignore WS
